<?php

$title = 'Add new movie';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Movie title');

$genre = $form->get('genre');
$genre->setAttribute('class', 'form-control');
$genre->setAttribute('placeholder', 'Genre');

$actors = $form->get('actors');
$actors->setAttribute('class', 'form-control');
$actors->setAttribute('placeholder', 'Actors');

$rating = $form->get('rating');
$rating->setAttribute('class', 'form-control');
$rating->setAttribute('placeholder', 'Rating');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('movie', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($genre) ?>
    <?= $this->formElement($genre) ?>
    <?= $this->formElementErrors()->render($genre, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($actors) ?>
    <?= $this->formElement($actors) ?>
    <?= $this->formElementErrors()->render($actors, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($rating) ?>
    <?= $this->formElement($rating) ?>
    <?= $this->formElementErrors()->render($rating, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();